# Basics of Python

In [ ]:
print('Harsh Pandey')

Harsh Pandey

In [ ]:
5+5

10

In [ ]:
import keyword
print(keyword.kwlist)

['False', 'None', 'True', 'and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']

In [ ]:
1_name = 'Harsh'

SyntaxError: ignored

In [ ]:
name@ = 'Harsh'

SyntaxError: ignored

In [ ]:
if=45

SyntaxError: ignored

In [ ]:
name='Harsh'

In [ ]:
name1 = 'Harsh'

In [ ]:
_name = 'Harsh'

In [ ]:
age = 30 # is used for single line comment
"""
class  = 10
name = 'harsh'      is used for multiple line comment
"""

age = 35

In [ ]:
price = 89000+56432
price

145432

In [ ]:
age = 50
if age==50:
  print("age of person is:",age)

age of person is: 50

In [ ]:
name = 'Harsh'
type(name)

str

In [ ]:
type(age)

int

In [ ]:
a = 7+3j
type(a)

complex

In [ ]:
accept=True
type(accept)

bool

In [ ]:
name

'Harsh'

In [ ]:
name[2]

'r'

In [ ]:
name[1:5]

'arsh'

In [ ]:
name[0:5]='Krish'         #Strings are immutable

TypeError: ignored

In [ ]:
del name        #delete a string

In [ ]:
name            #it is deleted

NameError: ignored

In [ ]:
n1 = "bhopal"

In [ ]:
n1.upper()

'BHOPAL'

In [ ]:
n1.lower()

'bhopal'

List

In [ ]:
companies=[]
type(companies)

list

In [ ]:
companies=['Wipro', 'IBM', 'TCS', 'META','Google', 21, 23, 30, 21, 25, 3.5, 4.5, 6.66, 25,26]       #Can contain different data types
companies

['Wipro',
 'IBM',
 'TCS',
 'META',
 'Google',
 21,
 23,
 30,
 21,
 25,
 3.5,
 4.5,
 6,
 25,
 26]

In [ ]:
companies=['Wipro', 'IBM', 'TCS', 'META','Google', [21, 23, 30, 21, 25], [3.5, 4.5, 6.66, 25,26]]       #Nested list
companies

['Wipro',
 'IBM',
 'TCS',
 'META',
 'Google',
 [[21, 23, 30, 21, 25], 3.5, 4.5, 6.66, 25, 26]]

In [ ]:
companies[4]

'Google'

In [ ]:
companies[5][2]

4.5

In [ ]:
companies[:3]

['Wipro', 'IBM', 'TCS']

In [ ]:
companies.append('Hyderabad')

In [ ]:
companies.insert(3,'Amazon')

In [ ]:
companies

['Wipro',
 'IBM',
 'TCS',
 'Amazon',
 'META',
 'Google',
 [[21, 23, 30, 21, 25], 3.5, 4.5, 6.66, 25, 26],
 'Hyderabad',
 'Hyderabad',
 'Hyderabad']

In [ ]:
companies.pop()
companies

['Wipro',
 'IBM',
 'TCS',
 'Amazon',
 'META',
 'Google',
 [[21, 23, 30, 21, 25], 3.5, 4.5, 6.66, 25, 26]]

In [ ]:
companies.remove('TCS')

In [ ]:
companies

['Wipro',
 'IBM',
 'Amazon',
 'META',
 'Google',
 [[21, 23, 30, 21, 25], 3.5, 4.5, 6.66, 25, 26]]

In [ ]:
companies.pop(5)

[[21, 23, 30, 21, 25], 3.5, 4.5, 6.66, 25, 26]

In [ ]:
companies

['Wipro', 'IBM', 'Amazon', 'META', 'Google']

In [ ]:
del companies

In [ ]:
companies

NameError: ignored

In [ ]:
odi=[433,233,587,345,674]

In [ ]:
odi.reverse()     #reversing the list
odi

[674, 345, 587, 233, 433]

In [ ]:
odi[::-1]         #reversing the list

[433, 233, 587, 345, 674]

In [ ]:
name='Harsh'                    #List comprehension
name=[i for i in name]
name

['H', 'a', 'r', 's', 'h']

In [ ]:
even = [i for i in range(40) if i%2==0]
even

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38]

Tuples

Ordered, Immutable, Allows Duplicates, Slicing, Indexing

In [ ]:
Tup = (1,'Harsh',12.33)       # () used for creating the tuple

In [ ]:
Tup[1]                        #Indexing starts with 0

'Harsh'

In [ ]:
Tup[1:3]

('Harsh', 12.33)

In [ ]:
tup = (1,'Harsh',12.45,1,2)     #Allowing the duplicates
tup

(1, 'Harsh', 12.45, 1, 2)

In [ ]:
tup[1] = 'Rohit'            #Immutable as we cannot change name from Harsh to Rohit

TypeError: ignored

Set

Does'nt allow duplicates, unordered, immutable, no indexing and slicing

In [ ]:
st = {1,1,'Harsh', 'Rohit',33.45,'Harish', 'Shivam', 34,'Harmesh'}            #{} used for set creation
st                    #Duplicate of 1 removed automatically

{1, 33.45, 34, 'Harish', 'Harmesh', 'Harsh', 'Rohit', 'Shivam'}

In [ ]:
st[1]         #Indexing not possible

TypeError: ignored

In [ ]:
st[1:5]       #No slicing possible

TypeError: ignored

Dictionary

Contains keys and their value {key: value}

It is mutable.

Slicing and Indexing is also allowed

Multiple values can be assigned to a single key but multiple keys are not possible.

***Dictionary are used to create python dataframe***

In [ ]:
dict = {1:'Harsh', 2:'Rohan', 3:'Harshit', 4:'Karan', 5:'VIT'}
dict

{1: 'Harsh', 2: 'Rohan', 3: 'Harshit', 4: 'Karan', 5: 'VIT'}

In [ ]:
type(dict)              #used to check type of variable

dict

In [ ]:
type(st)

set

In [ ]:
dict_1 = {1:['Harsh', 'Utkarsh'], 2:'VIT', 3:'Karnataka'}

In [ ]:
dict_1.keys()         #use to check keys in dictionary

dict_keys([1, 2, 3])

In [ ]:
dict_1.values()      #use to check values in dictionary

dict_values([['Harsh', 'Utkarsh'], 'VIT', 'Karnataka'])

In [ ]:
dict_1[3]           #calling key to get value

'Karnataka'

In [ ]:
dict_2 = {1:'Harsh','num1':'Karan', 2:'VIT'}            #We can give string as key also
dict_2.keys()

dict_keys([1, 'num1', 2])

In [ ]:
dict_3 = {'name':['Harsh', 'Utkarsh','karan','Kabir','Rahul', 'Rohan'],
          'org':['VIT', 'SRM', 'KIIT'],
          'main':'VIT'}

In [ ]:
dict_3['name']

['Harsh', 'Utkarsh', 'karan', 'Kabir', 'Rahul', 'Rohan']

In [ ]:
type(dict_3['name'])          #Use to check type of perticular keys and their values

list

In [ ]:
dict_3['name'][:4]            #Slicing of values associated with key

['Utkarsh', 'karan', 'Kabir']

In [ ]:
dict_3['name'][-4:]

['karan', 'Kabir', 'Rahul', 'Rohan']

# Pandas

In [ ]:
import pandas as pd

1D Array represent the Series and 2D Array Represent the Dataframe

In [ ]:
#Create a Series
ser = pd.Series([3,4,5,6,7,8])
ser

0    3
1    4
2    5
3    6
4    7
5    8
dtype: int64

In [ ]:
ser2=pd.Series(["apple", "mango", "banana", "plum"])
ser2

0     apple
1     mango
2    banana
3      plum
dtype: object

In [ ]:
ser2[1:3]

NameError: ignored

In [ ]:
ser3=pd.Series([5,6,7,8,9,10,11,12,13,14], index=['r1','r2','r3','r4','r5','r6','r7','r8','r9','r10'])

In [ ]:
ser3['r2':'r9']

r2     6
r3     7
r4     8
r5     9
r6    10
r7    11
r8    12
r9    13
dtype: int64

In [ ]:
df = pd.read_csv("mtcars.csv")
df

,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
5,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
11,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
12,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3
13,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
14,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
15,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
16,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
20,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1
21,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
22,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
23,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
24,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1
26,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2

In [ ]:
df.head()     #Used to check first 5 obervations of Dataset

,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [ ]:
df.tail()     #Used to check last 5 observations of Dataset

,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.9,1,1,5,2
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.5,0,1,5,4
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.5,0,1,5,6
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.6,0,1,5,8
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.6,1,1,4,2

In [ ]:
df.shape          #Used to check total number of obervation with paramaters
                  #Here there are 32 observation with 12 parameters

(32, 12)

In [ ]:
df.mpg          #used to view a perticular column all observations

0     21.0
1     21.0
2     22.8
3     21.4
4     18.7
5     18.1
6     14.3
7     24.4
8     22.8
9     19.2
10    17.8
11    16.4
12    17.3
13    15.2
14    10.4
15    10.4
16    14.7
17    32.4
18    30.4
19    33.9
20    21.5
21    15.5
22    15.2
23    13.3
24    19.2
25    27.3
26    26.0
27    30.4
28    15.8
29    19.7
30    15.0
31    21.4
Name: mpg, dtype: float64

In [ ]:
df['mpg']           #same as df.mpg but incase if space is there then use [' ']

0     21.0
1     21.0
2     22.8
3     21.4
4     18.7
5     18.1
6     14.3
7     24.4
8     22.8
9     19.2
10    17.8
11    16.4
12    17.3
13    15.2
14    10.4
15    10.4
16    14.7
17    32.4
18    30.4
19    33.9
20    21.5
21    15.5
22    15.2
23    13.3
24    19.2
25    27.3
26    26.0
27    30.4
28    15.8
29    19.7
30    15.0
31    21.4
Name: mpg, dtype: float64

## Dataframe from Scratch

In [ ]:
df1 = pd.DataFrame([[1,2,3,4,5,6],[2,3,4,5,6,7],[4,5,8,9,6,5]])       #used to create a dataframe from Scratch
df1

   0  1  2  3  4  5
0  1  2  3  4  5  6
1  2  3  4  5  6  7
2  4  5  8  9  6  5

In [ ]:
df1.columns = ['c1', 'c2', 'c3', 'c4', 'c5', 'c6']        #giving column names
df1.index = ['r1','r2','r3']                              #giving row names
df1

    c1  c2  c3  c4  c5  c6
r1   1   2   3   4   5   6
r2   2   3   4   5   6   7
r3   4   5   8   9   6   5

In [ ]:
d = {'name':['A', 'B', 'C', 'D', 'E'], 'age':[19,21,nan,34,25], 'gender':['M','F','M','F','F']}
#we get error as nan is not defined to we need to use np.nan

NameError: ignored

In [ ]:
import numpy as np
d = {'name':['A', 'B', 'C', 'D', 'E'], 'age':[19,21,np.nan,34,25], 'gender':['M','F','M','F','F']}
df3 = pd.DataFrame(d)
df3

  name   age gender
0    A  19.0      M
1    B  21.0      F
2    C   NaN      M
3    D  34.0      F
4    E  25.0      F

In [ ]:
df3.gender

0    M
1    F
2    M
3    F
4    F
Name: gender, dtype: object

In [ ]:
df3['Salary'] = [12000,14000,10000,56000,96000]     #Adding new Column

In [ ]:
df3

  name   age gender  Salary
0    A  19.0      M   12000
1    B  21.0      F   14000
2    C   NaN      M   10000
3    D  34.0      F   56000
4    E  25.0      F   96000

In [ ]:
df3.isnull().any()      #used to check any null values

name      False
age        True
gender    False
Salary    False
dtype: bool

In [ ]:
df3.isnull().sum()

name      0
age       1
gender    0
Salary    0
dtype: int64

In [ ]:
df3.shape

(5, 4)

In [ ]:
dff = df3.drop(['Salary'], axis=1)        #Droping a column
# Note if dropping any column then axis=1 and if row then axis = 0
# But we do not drop any row as more observation more accuracy
dff

  name   age gender
0    A  19.0      M
1    B  21.0      F
2    C   NaN      M
3    D  34.0      F
4    E  25.0      F

In [ ]:
df.info()     #used to know the DataType of Columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 12 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   model   32 non-null     int64
 1   mpg     32 non-null     float64
 2   cyl     32 non-null     int64
 3   disp    32 non-null     float64
 4   hp      32 non-null     int64
 5   drat    32 non-null     float64
 6   wt      32 non-null     float64
 7   qsec    32 non-null     float64
 8   vs      32 non-null     int64
 9   am      32 non-null     int64
 10  gear    32 non-null     int64
 11  carb    32 non-null     int64
dtypes: float64(5), int64(7)
memory usage: 3.1 KB

In [ ]:
df3.describe()       #used to get descriptive statistics
# we get only info of age and salary but not of name and gender as they are Categorical

             age        Salary
count   4.000000      5.000000
mean   24.750000  37600.000000
std     6.652067  37825.917041
min    19.000000  10000.000000
25%    20.500000  12000.000000
50%    23.000000  14000.000000
75%    27.250000  56000.000000
max    34.000000  96000.000000

In [ ]:
# Mean-Median :- Numerical feature
# Mode:- Categorical feature

print(df3.age.mean())
print(df3.age.median())

24.75
23.0

In [ ]:
df3.gender.mode()

0    F
Name: gender, dtype: object

In [ ]:
df3.age = df3.age.fillna(df3.age.median())    # used to fill missing value, we can use mean also
df3

  name   age gender  Salary
0    A  19.0      M   12000
1    B  21.0      F   14000
2    C  23.0      M   10000
3    D  34.0      F   56000
4    E  25.0      F   96000

Slicing Operators

Location (loc), Index Location (iloc)

In [ ]:
#Syntax
# loc[:,:]      Before comma is rows and after columns is rows
# iloc[:,:]

In [ ]:
df.loc[3]         #showing the obervation of 3rd index

model    Hornet 4 Drive
mpg                21.4
cyl                   6
disp              258.0
hp                  110
drat               3.08
wt                3.215
qsec              19.44
vs                    1
am                    0
gear                  3
carb                  1
Name: 3, dtype: object

In [ ]:
df.loc[1:3,'model':'hp']              #rows from 1st to 3rd and colunms from 'model' to 'hp'

            model   mpg  cyl   disp   hp
1   Mazda RX4 Wag  21.0    6  160.0  110
2      Datsun 710  22.8    4  108.0   93
3  Hornet 4 Drive  21.4    6  258.0  110

In [ ]:
df.iloc[1:3,0:5]                    #Before comma are rows and after comma are columns

           model   mpg  cyl   disp   hp
1  Mazda RX4 Wag  21.0    6  160.0  110
2     Datsun 710  22.8    4  108.0   93

In [ ]:
df.loc[0]

model    Mazda RX4
mpg           21.0
cyl              6
disp         160.0
hp             110
drat           3.9
wt            2.62
qsec         16.46
vs               0
am               1
gear             4
carb             4
Name: 0, dtype: object

In [ ]:
df.iloc[4]

model    Hornet Sportabout
mpg                   18.7
cyl                      8
disp                 360.0
hp                     175
drat                  3.15
wt                    3.44
qsec                 17.02
vs                       0
am                       0
gear                     3
carb                     2
Name: 4, dtype: object

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 12 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   model   32 non-null     object
 1   mpg     32 non-null     float64
 2   cyl     32 non-null     int64
 3   disp    32 non-null     float64
 4   hp      32 non-null     int64
 5   drat    32 non-null     float64
 6   wt      32 non-null     float64
 7   qsec    32 non-null     float64
 8   vs      32 non-null     int64
 9   am      32 non-null     int64
 10  gear    32 non-null     int64
 11  carb    32 non-null     int64
dtypes: float64(5), int64(6), object(1)
memory usage: 3.1+ KB

**Encoding**

Encoding is conversion of objects into int or float (i.e, strings/categorical values into int/float)

Types of Encoding:
1. One hot encoding
2. Label encoding
3. Manual encoding

Need for encoding is to pass data to algoritm for model training as it will only accept numerical data not categorical data

In [ ]:
# One Hot Encoding

pd.get_dummies(df['model'])       #get.dummies is used to encode categorical into numerical, but is not used frequently

# 0 means the model name is not present at that index whereas 1 means that name is present in pertical column for a perticular index

,AMC Javelin,Cadillac Fleetwood,Camaro Z28,Chrysler Imperial,Datsun 710,Dodge Challenger,Duster 360,Ferrari Dino,Fiat 128,Fiat X1-9,...,Merc 280C,Merc 450SE,Merc 450SL,Merc 450SLC,Pontiac Firebird,Porsche 914-2,Toyota Corolla,Toyota Corona,Valiant,Volvo 142E
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
6,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
11,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
12,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
13,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
14,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
17,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
18,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
20,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
21,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
22,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
24,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
25,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
26,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
27,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
28,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
29,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
30,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
31,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [ ]:
# Label Encoding
# need to use sklearn library and import LabelEncoder

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()     #initializing properties of LabelEncoder to a variable

In [ ]:
df3['gender'] = le.fit_transform(df3['gender'])
df3

  name   age  gender  Salary
0    A  19.0       1   12000
1    B  21.0       0   14000
2    C   NaN       1   10000
3    D  34.0       0   56000
4    E  25.0       0   96000

In [ ]:
df['model'] = le.fit_transform(df['model'])
df

    model   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
0      17  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
1      18  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4
2       4  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1
3      12  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3     1
4      13  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3     2
5      30  18.1    6  225.0  105  2.76  3.460  20.22   1   0     3     1
6       6  14.3    8  360.0  245  3.21  3.570  15.84   0   0     3     4
7      20  24.4    4  146.7   62  3.69  3.190  20.00   1   0     4     2
8      19  22.8    4  140.8   95  3.92  3.150  22.90   1   0     4     2
9      21  19.2    6  167.6  123  3.92  3.440  18.30   1   0     4     4
10     22  17.8    6  167.6  123  3.92  3.440  18.90   1   0     4     4
11     23  16.4    8  275.8  180  3.07  4.070  17.40   0   0     3     3
12     24  17.3    8  275.8  180  3.07  3.730  17.60   0   0     3     3
13     25  15.2    8  275.8  180  3.07  3.780  18.00   0   0     3     3
14      1  10.4    8  472.0  205  2.93  5.250  17.98   0   0     3     4
15     14  10.4    8  460.0  215  3.00  5.424  17.82   0   0     3     4
16      3  14.7    8  440.0  230  3.23  5.345  17.42   0   0     3     4
17      8  32.4    4   78.7   66  4.08  2.200  19.47   1   1     4     1
18     11  30.4    4   75.7   52  4.93  1.615  18.52   1   1     4     2
19     28  33.9    4   71.1   65  4.22  1.835  19.90   1   1     4     1
20     29  21.5    4  120.1   97  3.70  2.465  20.01   1   0     3     1
21      5  15.5    8  318.0  150  2.76  3.520  16.87   0   0     3     2
22      0  15.2    8  304.0  150  3.15  3.435  17.30   0   0     3     2
23      2  13.3    8  350.0  245  3.73  3.840  15.41   0   0     3     4
24     26  19.2    8  400.0  175  3.08  3.845  17.05   0   0     3     2
25      9  27.3    4   79.0   66  4.08  1.935  18.90   1   1     4     1
26     27  26.0    4  120.3   91  4.43  2.140  16.70   0   1     5     2
27     15  30.4    4   95.1  113  3.77  1.513  16.90   1   1     5     2
28     10  15.8    8  351.0  264  4.22  3.170  14.50   0   1     5     4
29      7  19.7    6  145.0  175  3.62  2.770  15.50   0   1     5     6
30     16  15.0    8  301.0  335  3.54  3.570  14.60   0   1     5     8
31     31  21.4    4  121.0  109  4.11  2.780  18.60   1   1     4     2